### ISSUE TITLE
Error Connecting Game

### ISSUE THREAD

**Issue by srtomy** [ChriisH/H1Z1-LoginServer#2]
when you open the game it is about 5 minutes and the error appears on the server

![image](https://user-images.githubusercontent.com/21697698/66247521-da92b580-e6f3-11e9-808b-5aa82f079b4a.png)

**Comment by lcplreaper** [comment]
The game is not complete. You won't be able to connect until Chriis has finished everything and uploaded the complete project.

**Comment by ChriisH** [comment]
The game is sending a disconnection message after 30 seconds being waiting for the external gateway server ip/port. Still need to create a new server for it and find out how they send the ip of the gateway server from the login server.

**Comment by srtomy** [comment]
thanks.
